### ISSUE TITLE
SD 1.5?

### ISSUE THREAD

**Issue by cian0** [text2cinemagraph/text2cinemagraph#3]
Would this work with SD1.5? This really looks awesome

**Comment by text2cinemagraph** [comment]
Hi @cian0! Thanks for your interest in our work.

Yes, our method can also work with SD1.5 (or any other 1.x models). The codebase for twin-image generation is based on [CompVis](https://github.com/CompVis/stable-diffusion)'s github repo, I will change it to [diffusers](https://github.com/huggingface/diffusers), so that it can be used with any huggingface model (based on 1.x). 

If you want to use SD1.5 for now, you can download the SD1.5 checkpoints from [here](https://huggingface.co/runwayml/stable-diffusion-v1-5), and convert them to the compatible verison using this conversion [script](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py). Please see this [issue](https://github.com/huggingface/diffusers/issues/672) for more details on how to convert. 
Once done, change the location in `configs/inference.yml` (and other places if required) from `img2img/models/ldm/stable-diffusion-v1/sd-v1-4-full-ema.ckpt` to the location of your converted `.ckpt` file.

**Comment by cian0** [comment]
Awesome, thanks!
