### ISSUE TITLE
Endless Loop *.gif

### ISSUE THREAD

**Issue by ryhhtn** [text2cinemagraph/text2cinemagraph#4]
Thank you very much for the interesting code!

I tried it and the result is not an Endless Loop Gif, but a 2 second movie.
Will you provide the code to generate the Endless Loop?

**Comment by text2cinemagraph** [comment]
The code currently generates a `.mp4` and not a `.gif`. The generated video is looping in the sense that if you play the video in a loop on any video player, it will appear to be looping without any jerk. For now, you can convert the `.mp4` to a `.gif` using this [website](https://ezgif.com/video-to-gif). We will add the option to generate a `.gif` instead of the `.mp4`.
